# https://github.com/robotology/gh-action-nightly-merge
name: 'Merge to develop'

on:
  push:
    branches:
      - master

jobs:
  merge-to-develop:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Merge master into develop
      uses: robotology/gh-action-nightly-merge@v1.3.3
      with:
        stable_branch: 'master'
        development_branch: 'developmay23'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.DOCSBUILDER_TOKEN }}
